import { NovaPlugin } from '../../types';
export declare class AdvancedCodeAssistant {
    private plugin;
    constructor();
    intelligentCompletion(code: string, cursorPosition: number, context: any): Promise<string>;
    generateFullFunction(description: string, language: string, context?: any): Promise<string>;
    refactorCode(code: string, refactoringType: string): Promise<string>;
    analyzeArchitecture(codebase: string[]): Promise<string>;
    debugCode(code: string, error: string, stackTrace?: string): Promise<string>;
    generateTests(code: string, testFramework: string): Promise<string>;
    reviewCode(code: string): Promise<string>;
    explainCode(code: string): Promise<string>;
    private analyzeCodeContext;
    private generateCompletions;
    private generateJavaScriptFunction;
    private generateTypeScriptFunction;
    private generatePythonFunction;
    private generateRustFunction;
    private generateGoFunction;
    private extractFunction;
    private optimizePerformance;
    private modernizeSyntax;
    private analyzeError;
    private generateSolutions;
    private assessCodeQuality;
    private identifySecurityIssues;
    private findLineAtPosition;
    private getIndentLevel;
    private isInFunction;
    private isInClass;
    private extractVariables;
    private extractImports;
    private generateFunctionName;
    private generateParameters;
    private generateTypedParameters;
    private generateReturnType;
    private generateFunctionBody;
    private generateRustParameters;
    private generateRustReturnType;
    private generateGoParameters;
    private generateGoReturnType;
    private findDuplicatedBlocks;
    private classifyError;
    private assessSeverity;
    private extractErrorLocation;
    private generateErrorDescription;
    private assessReadability;
    private assessMaintainability;
    private calculateCyclomaticComplexity;
    private assessDocumentation;
    private assessTestability;
    getPlugin(): NovaPlugin;
}
export default AdvancedCodeAssistant;
//# sourceMappingURL=AdvancedCodeAssistant.d.ts.map